"""Protocol -> report mapping. One entry per protocol, in README order.

`reports` are paths inside the Oak Security audit-reports repository. Severity
counts are never written here; they are parsed out of the PDFs by analyze.py.
"""

CATEGORIES = [
    ("L1 core, consensus and VMs", "l1"),
    ("Rollups, sequencers and settlement", "rollups"),
    ("Cross-chain, bridges and relayers", "crosschain"),
    ("Liquid staking and Bitcoin-linked", "staking"),
    ("DeFi", "defi"),
    ("Wallets, multisig and account abstraction", "wallets"),
    ("AI and verifiable compute", "ai"),
    ("Other", "other"),
]

PROTOCOLS = [
    {
        "slug": "stellar-core",
        "name": "Stellar Core",
        "cat": "l1",
        "stack": "C++/Rust, Soroban",
        "summary": "Consensus-protocol upgrades to the reference Stellar validator: SCP, overlay, buckets, transaction application and the Soroban host pipeline.",
        "role": "Reviewer on the protocol upgrade audits.",
        "reports": [
            "Stellar/2025-10-17 Audit Report - Stellar Core Protocol 23 Changes v1.0.pdf",
            "Stellar/2025-11-13 Audit Report - Stellar Core Protocol 24 Changes v1.0.pdf",
        ],
        "unpublished": "One further Stellar Core report is not public yet.",
        "extra_note": "+1 report not public",
        "unpublished_reports": 1,
    },
    {
        "slug": "gno",
        "name": "Gno",
        "cat": "l1",
        "stack": "GnoVM, Go, Tendermint variant",
        "summary": "Gno.land's execution layer: GnoVM determinism and gas metering, the Gno standard library, and the Tendermint2 consensus fork.",
        "role": "Reviewer across the sprint audits and the later updates round.",
        "reports": [
            "Gno/2025-01-17 Audit Report - Gno Sprint 1 v1.0.pdf",
            "Gno/2025-01-27 Audit Report - Gno Sprint 2 v1.0.pdf",
            "Gno/2025-03-25 Audit Report - Gno Sprint 3 v1.0.pdf",
            "Gno/2026-01-09 Audit Report - Gno Updates v1.0.pdf",
        ],
    },
    {
        "slug": "neutron",
        "name": "Neutron",
        "cat": "l1",
        "stack": "Cosmos SDK, Go, CosmWasm hooks",
        "summary": "Neutron's migration from an Interchain Security consumer chain to an independent chain: staking, slashing, revenue and the CosmWasm hook surface.",
        "role": "Reviewer on the independent-chain audit.",
        "reports": [
            "Neutron/2025-03-25 Audit Report - Neutron Independent Chain v1.0.pdf",
        ],
    },
    {
        "slug": "babylon",
        "name": "Babylon",
        "cat": "l1",
        "stack": "Cosmos SDK, Bitcoin timestamping, EOTS",
        "summary": "Bitcoin staking protocol: BTC checkpointing, finality providers, extractable one-time signatures (EOTS) and the incentive module.",
        "role": "Reviewer on the v1.1 to v2 upgrade audit.",
        "reports": [
            "Babylon/2025-06-12 Audit Report - Babylon v1.0.pdf",
        ],
    },
    {
        "slug": "paxi-network",
        "name": "Paxi Network",
        "cat": "l1",
        "stack": "Cosmos SDK",
        "summary": "Application-specific Cosmos SDK chain and its custom modules.",
        "role": "Reviewer.",
        "reports": [
            "Paxi/2025-11-01 Audit Report - Paxi Network.pdf",
        ],
    },
    {
        "slug": "dora-vota",
        "name": "Dora Vota",
        "cat": "l1",
        "stack": "Cosmos SDK, CosmWasm, Solidity",
        "summary": "Dora Factory's quadratic-funding chain: the vota chain modules and the contract migration path.",
        "role": "Reviewer.",
        "reports": [
            "DoraFactory/2024-06-13 Audit Report - Dora Vota v1.0.pdf",
            "DoraFactory/2024-09-23 Audit Report - Dora Vota Migration Contract v1.0.pdf",
        ],
    },
    {
        "slug": "xion",
        "name": "XION",
        "cat": "l1",
        "stack": "Cosmos SDK, CosmWasm, JWT/passkeys",
        "summary": "Burnt's chain-level account abstraction: smart accounts authenticated with JWTs, passkeys and secp256k1/r1 keys, plus the supporting contracts.",
        "role": "Reviewer across the contract and account-abstraction rounds.",
        "reports": [
            "Burnt (XION)/2023-09-22 Audit Report - XION and Burnt Contracts v1.1.pdf",
            "Burnt (XION)/2023-09-22 Audit Report - XION and Burnt Contract Updates and Account Abstraction v1.1.pdf",
            "Burnt (XION)/2024-05-25 Audit Report - XION and Account Abstraction Updates 2 v1.0.pdf",
        ],
    },
    {
        "slug": "osmosis-smart-accounts",
        "name": "Osmosis Smart Accounts",
        "cat": "l1",
        "stack": "Cosmos SDK, Go",
        "summary": "Osmosis authenticator framework: pluggable account authenticators evaluated in the ante handler.",
        "role": "Reviewer.",
        "reports": [
            "Osmosis Labs/2024-07-03 Audit Report - Osmosis Smart Accounts v1.0.pdf",
        ],
    },
    {
        "slug": "fairblock",
        "name": "FairBlock",
        "cat": "l1",
        "stack": "Cosmos SDK, identity-based encryption",
        "summary": "fairyring: pre-execution privacy through identity-based encryption, with keyshare distribution and decryption keyed to block height.",
        "role": "Reviewer.",
        "reports": [
            "Fairblock/2023-10-02 Audit Report - FairBlock fairyring v1.0.pdf",
        ],
    },
    {
        "slug": "skip-protocol",
        "name": "Skip Protocol",
        "cat": "l1",
        "stack": "Cosmos SDK, ABCI++",
        "summary": "Protocol-owned block building on ABCI++: proposal handlers, auction and bundle inclusion.",
        "role": "Reviewer.",
        "reports": [
            "Skip/2023-07-29 Audit Report - Skip Protocol Owned Builder v1.0.pdf",
        ],
    },
    {
        "slug": "agave-solana",
        "name": "Agave (Solana validator client)",
        "cat": "l1",
        "stack": "Rust, Solana consensus",
        "summary": "Consensus fork audit of a Solana validator client: fork choice and core system programs.",
        "role": "Reviewer. Client under NDA, report not published.",
        "reports": [],
        "unpublished": "Client under NDA; the report is not public.",
        "brand": "under NDA",
    },
    {
        "slug": "fuel-sequencer",
        "name": "Fuel Sequencer",
        "cat": "rollups",
        "stack": "Cosmos SDK, CometBFT, Ethereum event ingestion",
        "summary": "Fuel's shared sequencer: a CometBFT chain that ingests Ethereum bridge events, plus the surrounding infrastructure services.",
        "role": "Lead across 12 review rounds.",
        "reports": [],
        "unpublished": "Not published by the client.",
        "unpublished_reports": 12,
        "counts_note": "12 reports / 73+ findings, per my engagement records.",
    },
    {
        "slug": "dymension",
        "name": "Dymension",
        "cat": "rollups",
        "stack": "Cosmos SDK, Go",
        "summary": "RollApp settlement layer: the hub's rollapp/sequencer modules, the dymint client, virtual frontier contracts and a white-box RollApp pentest.",
        "role": "Reviewer across the Point 0D and Point 1D streams.",
        "reports": [
            "Dymension/2024-03-08 Audit Report - Dymension Point 0D v1.0.pdf",
            "Dymension/2024-04-30 Audit Report - Dymension Point 1D Stream 2_ Virtual Frontier Contract v1.1.pdf",
            "Dymension/2024-07-09 Audit Report - Dymension Point 1D Stream 3_ Dymint v1.1.pdf",
            "Dymension/2024-08-13 Audit Report - Dymension Point 1D Stream 6_ RollApp White-box Pentest v1.1.pdf",
        ],
        "unpublished": "Three further Dymension reports are not public.",
        "extra_note": "+3 reports not public",
        "unpublished_reports": 3,
    },
    {
        "slug": "zigchain",
        "name": "Zigchain",
        "cat": "rollups",
        "stack": "Cosmos SDK",
        "summary": "Zigchain's core modules over several rounds, reviewed diff-aware between releases.",
        "role": "Reviewer.",
        "reports": [
            "ZIGChain/2025-12-19 Audit Report - ZIGChain Update.pdf",
            "ZIGChain/2026-05-15 Audit Report – ZIGChain.pdf",
        ],
    },
    {
        "slug": "router-protocol",
        "name": "Router Protocol",
        "cat": "crosschain",
        "stack": "Cosmos SDK, CosmWasm, Go, Solidity, NEAR, Solana",
        "summary": "Router chain and the Voyager stack: the chain's cross-chain modules, orchestrator, asset bridge, DexSpan aggregator and the EVM/NEAR gateway contracts.",
        "role": "Lead across the chain, gateway and Voyager rounds.",
        "reports": [
            "Router/2022-11-27 Audit Report - Router v1.0.pdf",
            "Router/2024-04-29 Audit Report - Router Voyager Forwarder v1.0.pdf",
            "Router/2024-04-30 Audit Report - Router Asset Bridge v1.2.pdf",
            "Router/2024-04-30 Audit Report - Router Chain 2 v1.0.pdf",
            "Router/2024-04-30 Audit Report - Router Orchestrator v1.0.pdf",
            "Router/2024-04-30 Audit Report - Router Voyager Forwarder and CW Gateway v1.2.pdf",
            "Router/2024-05-10 Audit Report - Router DexSpan v1.0.pdf",
            "Router/2024-05-29 Audit Report - Router EVM and NEAR Gateway Contracts and WASM Bindings v1.0.pdf",
            "Router/2024-05-29 Audit Report - Router Integration v1.0.pdf",
        ],
        "unpublished": "Five further Router reports are not public.",
        "extra_note": "+5 reports not public",
        "unpublished_reports": 5,
    },
    {
        "slug": "snowbridge",
        "name": "Snowbridge",
        "cat": "crosschain",
        "stack": "Rust, Polkadot to Ethereum bridge",
        "summary": "Trustless Polkadot to Ethereum bridge. My round covered the Fiat-Shamir transform applied to the BEEFY light-client verification.",
        "role": "Reviewer.",
        "reports": [
            "Snowbridge/2025-12-29 Audit Report - Snowbridge Fiat Shamir Beefy Changes v1.0.pdf",
        ],
    },
    {
        "slug": "ics721",
        "name": "ICS721",
        "cat": "crosschain",
        "stack": "CosmWasm, IBC",
        "summary": "Interchain NFT transfer standard implemented in CosmWasm: the escrow/proxy contracts and the IBC callbacks.",
        "role": "Reviewer.",
        "reports": [
            "Public Awesome/2023-01-27 Audit Report - ICS721 v1.0.pdf",
        ],
    },
    {
        "slug": "the-rig",
        "name": "The Rig",
        "cat": "staking",
        "stack": "Fuel, Sway/Rust",
        "summary": "Liquid staking on Fuel, plus the follow-up round on the protocol updates.",
        "role": "Reviewer on both rounds.",
        "reports": [
            "The Rig/2025-07-01 Audit Report - The Rig v1.0.pdf",
            "The Rig/2025-10-01 Audit Report - The Rig Updates v1.1.pdf",
        ],
    },
    {
        "slug": "persistence-pstake",
        "name": "Persistence / pSTAKE",
        "cat": "staking",
        "stack": "Go services, Cobo MPC, Solidity",
        "summary": "The Persistence bridge: off-chain Go relayer services, custody integration and the Solidity side of the bridge.",
        "role": "Reviewer.",
        "reports": [
            "Persistence/2022-01-20 Audit Report - Persistence Bridge - v1.0.pdf",
        ],
    },
    {
        "slug": "eris-protocol",
        "name": "Eris Protocol",
        "cat": "staking",
        "stack": "CosmWasm, Terra",
        "summary": "Liquid staking hub and vote-escrow contracts on Terra.",
        "role": "Reviewer.",
        "reports": [
            "Eris Protocol/2023-02-15 Audit Report - Eris Protocol v1.0.pdf",
        ],
    },
    {
        "slug": "mars-protocol",
        "name": "Mars Protocol",
        "cat": "defi",
        "stack": "CosmWasm",
        "summary": "Mars money market across its generations: Red Bank, Fields of Mars, the Rover credit manager, Outposts, the Neutron deployment and Perps.",
        "role": "Reviewer across the engagement.",
        "reports": [
            "Mars/2022-02-17 Audit Report - Mars v1.0.pdf",
            "Mars/2022-02-17 Audit Report - Mars Periphery v1.0.pdf",
            "Mars/2022-02-17 Audit Report - Fields of Mars v1.0.pdf",
            "Mars/2022-12-09 Audit Report - Mars Rover v1.0.pdf",
            "Mars/2023-01-13 Audit Report - Mars Outposts v1.0.pdf",
            "Mars/2023-02-03 Audit Report - Mars Periphery v1.0.pdf",
            "Mars/2023-02-03 Audit Report - Mars Rover Updates v1.0.pdf",
            "Mars/2023-08-01 Audit Report - Mars Red Bank Updates v1.0.pdf",
            "Mars/2023-09-14 Audit Report - Mars Rover v2 v1.0.pdf",
            "Mars/2024-07-15 Audit Report - Mars v2 on Neutron v1.0.pdf",
            "Mars/2024-12-04 Audit Report - Mars Perps v1.0.pdf",
        ],
    },
    {
        "slug": "levana",
        "name": "Levana",
        "cat": "defi",
        "stack": "CosmWasm",
        "summary": "Levana perpetual swaps: the perps market, liquidity pool and liquidation logic.",
        "role": "Reviewer.",
        "reports": [
            "Levana/2022-05-03 Audit Report - Levana Perpetual Swaps v1.0.pdf",
        ],
    },
    {
        "slug": "frizzante",
        "name": "Frizzante",
        "cat": "defi",
        "stack": "CosmWasm",
        "summary": "Frizzante core contracts.",
        "role": "Reviewer.",
        "reports": [
            "Frizzante/2025-01-30 Audit Report - Frizzante Core Contracts v1.0.pdf",
        ],
    },
    {
        "slug": "autonomy-network",
        "name": "Autonomy Network",
        "cat": "defi",
        "stack": "CosmWasm",
        "summary": "Automation network on Osmosis: registry, executors and the limit-order integration.",
        "role": "Reviewer.",
        "reports": [
            "Autonomy/2023-03-06 Audit Report - Autonomy Osmosis v1.1.pdf",
        ],
    },
    {
        "slug": "volta",
        "name": "Volta",
        "cat": "wallets",
        "stack": "CosmWasm, Soroban",
        "summary": "Multisig wallet contracts, first on CosmWasm and then the Soroban port.",
        "role": "Reviewer on both rounds.",
        "reports": [
            "Volta/2024-09-18 Audit Report - Volta CosmWasm v1.0.pdf",
            "Volta/2025-11-19 Audit Report - Volta Soroban.pdf",
        ],
    },
    {
        "slug": "vectis",
        "name": "Vectis",
        "cat": "wallets",
        "stack": "CosmWasm",
        "summary": "Smart-contract wallet with guardians, relayed transactions and plugin extensions.",
        "role": "Reviewer.",
        "reports": [
            "Vectis/2024-03-14 Audit Report - Vectis v1.0.pdf",
        ],
    },
    {
        "slug": "aixblockchain",
        "name": "AIxBlockchain",
        "cat": "ai",
        "stack": "Verifiable inference",
        "summary": "Verifiable inference work. Engagement delivered under a different brand.",
        "role": "Reviewer.",
        "reports": [],
        "unpublished": "Reports are not published yet.",
        "brand": "other brand",
    },
    {
        "slug": "nym",
        "name": "Nym",
        "cat": "other",
        "stack": "CosmWasm",
        "summary": "Mixnet and vesting contracts: node bonding, delegation rewards and the vesting account logic.",
        "role": "Reviewer.",
        "reports": [
            "Nym/2023-03-27 Audit Report - Nym Mixnet and Vesting Contracts v1.0.pdf",
        ],
    },
    {
        "slug": "spice-quest",
        "name": "Spice Quest",
        "cat": "other",
        "stack": "CosmWasm",
        "summary": "CosmWasm contracts.",
        "role": "Reviewer.",
        "reports": [],
        "unpublished": "Report not published.",
        "unpublished_reports": 1,
        "counts_note": "1 report / 18 findings, per my engagement records.",
    },
    {
        "slug": "mantra-chain",
        "name": "Mantra Chain",
        "cat": "other",
        "stack": "Cosmos SDK",
        "summary": "MANTRA Chain v5.0.0: the chain upgrade reviewed in phases.",
        "role": "Reviewer.",
        "reports": [
            "MANTRA/2025-11-03 Audit Report - MANTRA Chain v5.0.0 Phases 1-3 v1.3.pdf",
        ],
    },
    {
        "slug": "hyvechain",
        "name": "Hyvechain",
        "cat": "other",
        "stack": "Cosmos SDK, EVM precompiles",
        "summary": "Hyvechain precompiles: the EVM precompile surface exposed over native chain modules.",
        "role": "Reviewer.",
        "reports": [
            "Hyvechain precompiles/2026-05-15 Audit Report - Hyvechain precompiles v1.0.pdf",
        ],
    },
    {
        "slug": "emi-wallet",
        "name": "EMI wallet (architecture review)",
        "cat": "other",
        "stack": "Custody, settlement, brokerage",
        "summary": "Architecture and control mapping for a large electronic money institution: custody, cross-border settlement and brokerage.",
        "role": "Lead. Client under NDA, no public report.",
        "reports": [],
        "unpublished": "Client under NDA; no public report.",
        "brand": "under NDA",
    },
]
